#ifndef __YM2151_H__
#define __YM2151_H__

enum ym_param {
	YMVAL_TEST,YMVAL_KON,YMVAL_NE,YMVAL_NFRQ,YMVAL_CLKA1,YMVAL_CLKA2,
	YMVAL_CLK2,YMVAL_CSM,YMVAL_TRESET,YMVAL_IRQEN,YMVAL_LOADT,YMVAL_LFRQ,
	YMVAL_PMD,YMVAL_AMD,YMVAL_CT,YMVAL_W,YMVAL_RL,YMVAL_FB,YMVAL_CONECT,
	YMVAL_KC,YMVAL_KF,YMVAL_PMS,YMVAL_AMS,YMVAL_DT1,YMVAL_MUL,YMVAL_TL,
	YMVAL_KS,YMVAL_AR,YMVAL_AMSEN,YMVAL_D1R,YMVAL_DT2,YMVAL_D2R,YMVAL_D1L,
	YMVAL_RR
};

#endif
